### ISSUE TITLE
NCAA casablanca endpoint

### ISSUE THREAD

**Issue by joshcvt** [joshcvt/resetter#4]
https://data.ncaa.com/casablanca/scoreboard/football/fbs/2018/P/scoreboard.json
--

flips to P after week 15
the JSON is different

**Comment by joshcvt** [comment]
NCAAF module is completely unusable until I rewrite to the new endpoint

**Comment by flynneva** [comment]
I use the same casablanca server for basketball data over on my [react-ncaa-data](https://github.com/flynneva/react-ncaa-data.got) repo and was wondering if you'd be interested in if I added football to that as well?

**Comment by flynneva** [comment]
I'm also figuring out the server api the same as you, are you just guessing/checking or are you going off some sort of document?

**Comment by joshcvt** [comment]
Looks neat -- I haven't worked with React personally, but I'm always interested in cool stuff others are working on. 

This entire project is guess-and-check -- I haven't gotten the NCAAF module back into working order because capturing JSON states hasn't been top use of my Thursday nights or Saturdays the last couple seasons.

**Comment by flynneva** [comment]
I've been doing the same, guess-and-check the api call until it works 😅 what's tricky is that each sport seems to have its own way of doing it. Kind of frustrating if you're writing software for many different sports.

Anyways I'll be following your stuff with football to see what you figure out. great stuff so far 👍🏼
